COMP	   = gnu

DIM        = 3

USE_MPI    = TRUE
DEBUG      = FALSE

PROFILE    = TRUE

USE_RAD = TRUE
USE_NEUTRINO = FALSE

CASTRO_HOME = ../../..

EOS_DIR     := gamma_law

NETWORK_DIR := general_null
NETWORK_INPUTS := gammalaw.net

Opacity_dir := null

Bpack   := ./Make.package
Blocs   := .

include $(CASTRO_HOME)/Exec/Make.Castro
