
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

static std::string gravity_type;
static amrex::Real const_grav;
static int direct_sum_bcs;
static int drdxfac;
static int lnum;
static int verbose;
static int no_sync;
static int no_composite;
static int do_composite_phi_correction;
static int get_g_from_phi;
static int mlmg_max_fmg_iter;
static int mlmg_agglomeration;
static int mlmg_consolidation;
static int mlmg_nsolve;
