
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

pp.query("gravity_type", gravity_type);
pp.query("const_grav", const_grav);
pp.query("direct_sum_bcs", direct_sum_bcs);
pp.query("drdxfac", drdxfac);
pp.query("max_multipole_order", lnum);
pp.query("v", verbose);
pp.query("no_sync", no_sync);
pp.query("no_composite", no_composite);
pp.query("do_composite_phi_correction", do_composite_phi_correction);
pp.query("max_solve_level", max_solve_level);
pp.query("get_g_from_phi", get_g_from_phi);
