
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

std::string Gravity::gravity_type = "fillme";
amrex::Real Gravity::const_grav = 0.0;
int         Gravity::direct_sum_bcs = 0;
int         Gravity::drdxfac = 1;
int         Gravity::lnum = 0;
int         Gravity::verbose = 0;
int         Gravity::no_sync = 0;
int         Gravity::no_composite = 0;
int         Gravity::do_composite_phi_correction = 1;
int         Gravity::max_solve_level = MAX_LEV-1;
int         Gravity::get_g_from_phi = 0;
