
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

pp.query("particle_init_file", particle_init_file);
pp.query("v", verbose);
pp.query("particle_restart_file", particle_restart_file);
pp.query("restart_from_nonparticle_chkfile", restart_from_nonparticle_chkfile);
pp.query("particle_output_file", particle_output_file);
pp.query("timestamp_dir", timestamp_dir);
