
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

int         Castro::particle_verbose = 0;
std::string Castro::particle_init_file = "";
std::string Castro::particle_restart_file = "";
int         Castro::restart_from_nonparticle_chkfile = 0;
std::string Castro::particle_output_file = "";
std::string Castro::timestamp_dir = "";
int         Castro::timestamp_density = 1;
int         Castro::timestamp_temperature = 0;
