
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

static int particle_verbose;
static std::string particle_init_file;
static std::string particle_restart_file;
static int restart_from_nonparticle_chkfile;
static std::string particle_output_file;
static std::string timestamp_dir;
static int timestamp_density;
static int timestamp_temperature;
