
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

std::string Particles::particle_init_file = "";
int         Particles::v = 0;
std::string Particles::particle_restart_file = "";
int         Particles::restart_from_nonparticle_chkfile = 0;
std::string Particles::particle_output_file = "";
std::string Particles::timestamp_dir = "";
