
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

int         RadSolve::level_solver_flag = 1;
int         RadSolve::use_hypre_nonsymmetric_terms = 0;
amrex::Real RadSolve::reltol = 1.e-10;
amrex::Real RadSolve::abstol = 1.e-10;
int         RadSolve::maxiter = 40;
amrex::Real RadSolve::alpha = 1.0;
amrex::Real RadSolve::beta = 1.0;
int         RadSolve::verbose = 0;
