
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

pp.query("level_solver_flag", level_solver_flag);
pp.query("use_hypre_nonsymmetric_terms", use_hypre_nonsymmetric_terms);
pp.query("reltol", reltol);
pp.query("abstol", abstol);
pp.query("maxiter", maxiter);
pp.query("alpha", alpha);
pp.query("beta", beta);
pp.query("v", verbose);
