COMP	   = g++
FCOMP	   = gfortran

#DIM        = 1
DIM        = 2
#DIM        = 3

DEBUG      = FALSE
#DEBUG      = TRUE

PROFILE    = FALSE

USE_NEUTRINO = FALSE

EOS_dir     := gamma_law
Network_dir := general_null
Network_inputs  := gammalaw.net
Opacity_dir := null

Bpack   := ./Make.package
Blocs   := .

include ../Make.Castro
