
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE
#DEBUG      = TRUE

DIM        = 1

COMP	   = g++
FCOMP	   = gfortran

USE_MPI    = TRUE

USE_GRAV   = TRUE
USE_HYPRE  = TRUE
USE_RAD    = TRUE
USE_NEUTRINO = FALSE

EOS_dir     = breakout
Network_dir = breakout
Opacity_dir = breakout

# use radiation interpbndry
RAD_INTERP = TRUE

Bpack   := ./Make.package
Blocs   := .

include ../Make.Castro
