#ifndef CASTRO_RADTYPES_H
#define CASTRO_RADTYPES_H

enum RadNames { Rad = 0 };
enum TestNames {
    Test0 = 0,
    Test1 = 1,
    Test2 = 2,
    Test3 = 3,
    Test4 = 4,
    Test5 = 5,
    Test6 = 6,
    Test7 = 7,
    Test8 = 8,
    Test9 = 9,
    Test10 = 10,
    Test11 = 11,
    Test12 = 12,
    Test13 = 13,
    Test14 = 14,
    Test15 = 15,
    Test16 = 16,
    Test17 = 17,
    Test18 = 18,
    Test19 = 19,
    Test20 = 20
};

#endif /* _RadTypes_H_ */
