PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE

DIM        = 1

COMP	   = g++
FCOMP	   = gfortran

USE_MPI    = FALSE

USE_REACT  = TRUE

CASTRO_DIR = ../..

# This sets the EOS directory in $(CASTRO_DIR)/EOS
EOS_dir     := helmeos

# This sets the EOS directory in $(CASTRO_DIR)/Networks
NETWORK_HOME := $(MICROPHYSICS_DIR)/networks
Network_dir := aprox13

Bpack   := ./Make.package
Blocs   := .

include ../Make.Castro
