COMP	   = g++
FCOMP	   = gfortran

DIM        = 1

DEBUG      = FALSE
#DEBUG      = TRUE

PROFILE    = FALSE

USE_GRAV   = TRUE

USE_NEUTRINO = FALSE

EOS_dir     = breakout
Network_dir = breakout
Opacity_dir = breakout

Bpack   := ./Make.package
Blocs   := .

include ../Make.Castro
