COMP	   = gnu

DIM        = 1

USE_MPI    = TRUE
DEBUG      = FALSE

PROFILE    = FALSE

USE_GRAV   = TRUE

USE_RAD = TRUE

CASTRO_HOME = ../../..

EOS_DIR     = breakout
NETWORK_DIR = breakout
Opacity_dir = breakout

Bpack   := ./Make.package
Blocs   := .

include $(CASTRO_HOME)/Exec/Make.Castro
