COMP	   = g++
FCOMP	   = gfortran

DIM        = 1

USE_MPI    = TRUE
DEBUG      = FALSE

PROFILE    = FALSE

USE_GRAV   = TRUE

USE_RAD = TRUE
USE_NEUTRINO = FALSE

CASTRO_HOME = ../../..

EOS_dir     = breakout
Network_dir = breakout
Opacity_dir = breakout

Bpack   := ./Make.package
Blocs   := .

include $(CASTRO_HOME)/Exec/Make.Castro
