
MathJax.Hub.Config({
    TeX: {
        Macros: {
            kth: '{{k_\\mathrm{th}}}',
            gcc: '{\\mathrm{g~cm^{-3}}}',
            cms: '{\\mathrm{cm~s^{-1}}}',
            presunit: '{\\mathrm{dyn~cm^{-2}}}',
            accelunit: '{\\mathrm{cm~s^{-2}}}',
            ergg: '{\\mathrm{erg~g^{-1}}}',
            Ab: '{{\\bf A}}',
            eb: '{{\\bf e}}',
            Fb: '{{\\bf F}}',
            gb: '{{\\bf g}}',
            Hb: '{{\\bf H}}',
            ib: '{{\\bf i}}',
            Ib: '{{\\bf I}}',
            Kb: '{{\\bf K}}',
            lb: '{{\\bf l}}',
            Lb: '{{\\bf L}}',
            nb: '{{\\bf n}}',
            Pb: '{{\\bf P}}',
            Qb: '{{\\bf Q}}',
            rb: '{{\\bf r}}',
            Rb: '{{\\bf R}}',
            Sb: '{{\\bf S}}',
            ub: '{{\\bf u}}',
            Ub: '{{\\bf U}}',
            xb: '{{\\bf x}}',
            dt: '{\\Delta t}',
            omegadot: '{\\dot\\omega}',
            inp: '{{\\rm in}}',
            outp: '{{\\rm out}}',
            sync: '{{\\rm sync}}',
            half: '{\\frac{1}{2}}',
            myhalf: '{\\half}',
            nph: '{{n+\\myhalf}}',
            kpp: '{\\ensuremath{\\kappa_{\\mathrm{P}}}}',
            kpr: '{\\ensuremath{\\kappa_{\\mathrm{R}}}}',
            kpf: '{\\ensuremath{\\kappa_{\\mathrm{F}}}}',
            vb: '{\\boldsymbol{v}}',
            vbt: '{\\widetilde{\\vb}}',
            rbt: '{\\widetilde{\\rb}}',
            ob: '{\\boldsymbol{\\omega}}',
            nablab: '{\\boldsymbol{\\nabla}}',

        }
    }
});

