
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE
DEBUG      = TRUE

DIM        = 1

COMP	   = g++
FCOMP	   = gfortran

USE_MPI    = TRUE

USE_GRAV   = FALSE
USE_HYPRE  = TRUE
USE_RAD    = TRUE
USE_NEUTRINO = FALSE

EOS_dir     := gamma_law_general
Network_dir := general_null
Network_inputs  := gammalaw.net
Opacity_dir := null

# use radiation interpbndry
RAD_INTERP = TRUE

Bpack   := ./Make.package
Blocs   := .

include ../Make.Castro
