FCOMP = gfortran

default: bc.ex

bc.ex: o/bltypes.o o/constant_cgs.o o/blackbody.o o/bc.o
	$(FCOMP) -o $@ $^

o/bltypes.o: ../../../../fParallel/boxlib/bl_types.f90
	$(FCOMP) -c -o $@ $^

o/constant_cgs.o: ../../../../fParallel/extern/constants/constants_cgs.f90 
	$(FCOMP) -c -o $@ $^

o/blackbody.o: ../../Source/Radiation/blackbody.f90 
	$(FCOMP) -c -o $@ $^

o/bc.o: bc.f90
	$(FCOMP) -c -o $@ $^

clean:
	rm -f o/bltypes.o o/constant_cgs.o o/blackbody.o o/bc.o

