COMP	   = g++
FCOMP      = gfortran
#COMP	   = Intel
#FCOMP	   = Intel

DIM        = 1
#DIM        = 2
#DIM        = 3

DEBUG      = FALSE
DEBUG      = TRUE

PROFILE    = FALSE

USE_NEUTRINO = TRUE

USE_GRAV     = TRUE

EOS_dir     := collapse
Network_dir := collapse
Opacity_dir := burrows

Bpack   := ./Make.package
Blocs   := .

include ../Make.Castro

