COMP	   = g++
FCOMP	   = gfortran

DIM        = 1

DEBUG      = FALSE

PROFILE    = FALSE

USE_NEUTRINO = FALSE

EOS_dir     := gamma_law
Network_dir := general_null
Network_inputs  := gammalaw.net
Opacity_dir := null

Bpack   := ./Make.package
Blocs   := .

include ../Make.Castro

