COMP	   = g++
FCOMP	   = gfortran

DIM        = 1

USE_MPI    = TRUE
DEBUG      = TRUE

PROFILE    = FALSE

USE_RAD = TRUE
USE_NEUTRINO = FALSE

CASTRO_HOME = ../..

EOS_dir     := gamma_law

Network_dir := general_null
NETWORK_INPUTS := gammalaw.net

Opacity_dir := null

Bpack   := ./Make.package
Blocs   := .

include ../Make.Castro
