#!/bin/bash
#PBS -A ast106sbu
#PBS -N sedov-1536-scale
#PBS -j oe
#PBS -l walltime=0:20:00,nodes=1728
#PBS -q batch
#PBS -l gres=atlas1%atlas2

cd $PBS_O_WORKDIR

export OMP_NUM_THREADS=2

# -n number of MPI tasks
# -N number of PEs per node 
# -d number of CPUs per PE -- this should be the number of threads
# -j number of CPUs to use per compute unit (since 2 PE share an FPU, we may want to reduce this)
aprun -n 13824 -N 8 -d 2 -j 2 ./Castro3d.pgi.interlagos.MPI.OMP.ex inputs.starlord

