#!/bin/bash

if command -v clang-format >/dev/null 2>&1; then

    export PATH=`git rev-parse --git-dir`/../tools/:$PATH

    git clang-format --extensions cpp,h,H --style file -v Source/driver
    # Possible predefined styles:
    # LLVM
    # Google
    # Chromium
    # Mozilla
    # WebKit

    # Change the code with:
    # git clang-format --extensions cpp,hpp -style=llvm -v


    rc=$?
    if [[ $rc == 33 ]]
    then
        echo "Nothing needs to be reformatted!"
        exit 0
    fi

    echo -e "Would you like to continue to commit (y/n): \c"

    # Make sure under any mode, we can read user input.
    exec < /dev/tty
    read cont

    if [ "$cont" == "y" ]
    then
        exit 0
    fi

    exit 1

else
	exit 0
fi
