COMP	   = gnu

DIM        = 1

USE_MPI    = TRUE
DEBUG      = FALSE

PROFILE    = FALSE

USE_RAD = TRUE
USE_NEUTRINO = TRUE

USE_GRAV     = TRUE

CASTRO_HOME = ../../..

# data in the following directories are not public available 
EOS_dir     := collapse
Network_dir := collapse
Opacity_dir := burrows

Bpack   := ./Make.package
Blocs   := .

include $(CASTRO_HOME)/Exec/Make.Castro

