
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

Real        Castro::const_grav = 0.0;
int         Castro::direct_sum_bcs = 0;
int         Castro::drdxfac = 1;
int         Castro::lnum = 0;
int         Castro::verbose = 0;
int         Castro::no_sync = 0;
int         Castro::no_composite = 0;
int         Castro::max_solve_level = MAX_LEV-1;
int         Castro::max_multipole_moment_level = 0;
int         Castro::get_g_from_phi = 0;
