
// This file is automatically created by parse_castro_params.py.  To update
// or add runtime parameters, please edit _cpp_parameters and then run
// mk_params.sh

static std::string gravity_type;
static Real const_grav;
static int direct_sum_bcs;
static int drdxfac;
static int lnum;
static int verbose;
static int no_sync;
static int no_composite;
static int max_solve_level;
static int max_multipole_moment_level;
static int get_g_from_phi;
