
#include <iomanip>
#include <iostream>

#ifdef _OPENMP
#include <omp.h>
#endif

using std::cout;                     
using std::cin;                     
using std::endl;                     
using std::ios;                     
using std::cerr; 
using std::string;
using std::vector;
using std::list;
using std::min;
using std::max;
using std::pair;
using std::flush;
using std::ofstream;
using std::ostream;
using std::istream;
using std::setprecision;
using std::setw;
