
PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = TRUE
DEBUG      = FALSE

#DIM        = 1
#DIM        = 2
DIM        = 3

COMP	   = gcc
FCOMP	   = gfortran

USE_MPI    = FALSE
USE_OMP    = FALSE

# This sets the EOS directory in Castro/EOS
EOS_dir     := gamma_law_general

# This sets the network directory in $(FBOXLIB_HOME)/extern/networks
Network_dir := gammalaw

Bpack   := ./Make.package
Blocs   := .

include ../Make.Castro
