name: "clang-tidy"

on: [pull_request]
jobs:
  clang_tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get submodules
        run: |
          git submodule update --init
          cd external/Microphysics
          git fetch; git checkout development
          cd ../amrex
          git fetch; git checkout development
          cd ../..

      - name: Install dependencies
        run: |
          .github/workflows/dependencies_clang-tidy-apt-llvm.sh 17

      - name: Compile flame_wave
        run: |
          cd Exec/science/subchandra
          make USE_CLANG_TIDY=TRUE CLANG_TIDY=clang-tidy-17 CLANG_TIDY_WARN_ERROR=TRUE -j 4

