name: docs build

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pandoc and doxygen
        run: |
          sudo apt install pandoc doxygen

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Build docs
        run: |
          cd Docs/
          make SPHINXOPTS=-v NO_DOXYGEN=TRUE html

      - name: Check links
        run: |
          cd Docs/
          make SPHINXOPTS=-v NO_DOXYGEN=TRUE linkcheck
