name: github pages

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc and doxygen
        run: |
          sudo apt update
          sudo apt install pandoc doxygen

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: python3 -m pip install -r ./requirements.txt

      - name: Build docs
        if: ${{ endsWith(github.ref, 'main') }}
        env:
          GITHUB_BRANCH: 'main'
        run: ./deploy_docs_action.sh

      - name: Build docs
        if: ${{ endsWith(github.ref, 'development') }}
        env:
          GITHUB_BRANCH: 'development'
        run: ./deploy_docs_action.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          keep_files: true
