name: model parser

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  model_parser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Get submodules
        run: |
          git submodule update --init
          cd external/Microphysics
          git fetch; git checkout development
          cd ../amrex
          git fetch; git checkout development
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install g++

      - name: Compile model_parser test
        run: |
          cd Util/model_parser/test
          make -j 4

      - name: Run model_parser test
        run: |
          cd Util/model_parser/test
          ./Castro3d.gnu.ex
