name: Rad2Tshock

on: [pull_request]
jobs:
  Rad2Tshock-1d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get submodules
        run: |
          git submodule update --init
          cd external/Microphysics
          git fetch; git checkout development
          cd ../amrex
          git fetch; git checkout development
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++>=9.3.0 hypre

      - name: Compile Rad2Tshock
        run: |
          cd Exec/radiation_tests/Rad2Tshock
          make DEBUG=TRUE USE_MPI=FALSE DIM=1 -j 4
