name: Sedov

on: [pull_request]
jobs:
  Sedov-3d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get submodules
        run: |
          git submodule update --init
          cd external/Microphysics
          git fetch; git checkout development
          cd ../amrex
          git fetch; git checkout development
          cd ../..

      - name: Install dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get -qq -y install curl cmake jq clang g++>=9.3.0

      - name: Compile Sedov
        run: |
          cd Exec/hydro_tests/Sedov
          make DEBUG=TRUE USE_MPI=FALSE -j 4

      - name: Run Sedov
        run: |
          cd Exec/hydro_tests/Sedov
          ./Castro3d.gnu.DEBUG.ex inputs.3d.sph max_step=10 amr.max_level=2 amr.plot_files_output=0 amr.checkpoint_files_output=0

      - name: Compare to stored output
        run: |
          cd Exec/hydro_tests/Sedov
          diff grid_diag.out ci-benchmarks/grid_diag.out
